#Должно быть вам не стоит делать свой прототип не изучив код основных систем но я подскажу вам как пользоваться

- type: sectorSystemPrototype # базовый прототип в C# там описаны все возможные методы для создания прототипа сектора
  id: AsteroidSectorDefault # ID нашего будущего сектора
  name: "Поле Астероидов" # Название нашего сектора, будет видно в БСС карте
  station: Beacon # id прототипа нашего грида, основной карты сектора, будь то маяк норд или тортуга
  worldgenConfig: AsteroidSectorDefault # будут ли в нашем секторе спавнится астероиды, тут указывается тип спавна астероидов, есть 2 типа Default где их минимум и AsteroidSectorDefault, где их обилие и большие размеры
  autoStart: true # Необходим для основной группы секторов, более понятно для чего и зачем не буду пояснять, просто включайте если используете в стандартном режиме игры, выключить если не нужно загружать сектор
  defaultGamePreset: NFPirates # Режим игры который мы используем по дефолту на нашем фронтире
  parallaxPool: [ MercenaryPlanet, LuaDarkSpace, LuaSpace, AspidParallax, BagelStation, CoreStation, OriginStation, TrainStation, KettleStation, Sky, Asteroids, Default ] # задний фон сектора, выбирается случайным образом
  deadDropEnabled: true # Включаем систему DeadDrop для сектора
  deadDropCount: 8 # Максимальное количество DeadDrop на сектор
  starmapPosition: 3.0, 4.8 # Позиция на StarMap
  starmapColor: "#c3cf18" # Цвет на StarMap
  poiGroups: # Ниже перечисляем точки интереса что будут раундстартом в секторе, их id и настройку можно получить из PointOfInterest в папке NF прототипов (либо Lua)
  - group: AsteroidRequired # Группа рекомендаций сектора
    count: 0 # если 0 то спавнится каждый по одному
  - group: CargoDepot
    count: 4
    ring: true # Спавн по окружности вокруг цвентра
  - group: AsteroidMarketStation
    count: 2
#Я рассказал базовые настройки на основе главного сектора, дальше ничего особого, я упростил код и дал больше инструментов но я крайне рекомендую быть осторожным при создании секторов, данная логика и её поведение непредсказуемое, я постарался сделать больше фоллбеков чтобы обезопасить сервер от возможных проблем но человеческий фактор непредсказуем.

- type: sectorSystemPrototype
  id: TypanSector
  name: "Сектор Нордфолл"
  station: Typan
  worldgenConfig: Default
  autoStart: true
  defaultGamePreset: NFPirates
  parallaxPool: [ OriginStation, NordFoll ]
  deadDropEnabled: false
  poiGroups:
  - group: TypanCargoDepot
    count: 1
    ring: false
  starmapPosition: 14.9, 12.0
  starmapColor: "#990816"

- type: sectorSystemPrototype
  id: PirateSector
  name: "Сектор Пиратов"
  station: Cove
  autoStart: true
  defaultGamePreset: NFPirates
  parallaxPool: [ CoreStation, Tortuga ]
  deadDropEnabled: true
  deadDropCount: 2
  starmapPosition: 17.6, -16.5
  starmapColor: "#8A6642"

- type: sectorSystemPrototype
  id: MercenarySector
  name: "Сектор Наёмников"
  station: MercMap
  autoStart: true
  defaultGamePreset: NFPirates
  parallaxPool: [ MercenaryPlanet, Sky ]
  deadDropEnabled: true
  deadDropCount: 1
  starmapPosition: -14.8, -16.2
  starmapColor: "#182faf"

- type: sectorSystemPrototype
  id: ShipVsShipRed
  name: "Сектор Красных"
  station: ShipVsShipRedGrid
  requiredGamePreset: ShipVsShip
  parallaxPool: [ LuaDarkSpace ]
  poiGroups:
  - group: ShipVsShipRedRequired
    count: 1

- type: sectorSystemPrototype
  id: ShipVsShipBlue
  name: "Сектор Синих"
  station: ShipVsShipBlueGrid
  requiredGamePreset: ShipVsShip
  parallaxPool: [ LuaDarkSpace ]
  poiGroups:
  - group: ShipVsShipBlueRequired
    count: 1
